#!/bin/bash

#################################
## Begin of user-editable part ##
#################################

POOL=beam-us.leafpool.com
PORT=3333
WALLET=55d621af7ce0c1485525ba2d17991cf82e5cc09b665cda785f42144927c8d9dfd2
COIN=BEAM

#################################
##  End of user-editable part  ##
#################################

cd "$(dirname "$0")"

./lolMiner --coin $COIN --pool $POOL --port $PORT --user $WALLET $@
